"""second

Revision ID: fe3e8b971df7
Revises: 5602f8e66ba9
Create Date: 2020-09-04 19:16:14.365209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe3e8b971df7'
down_revision = '5602f8e66ba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nigga', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'nigga')
    # ### end Alembic commands ###
